/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pengontrak;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.objects.NativeError.printStackTrace;
import model.*;


/**
 *
 * @author fikriadriansa21
 */
public class MenuPengontrakInternalFrame extends javax.swing.JInternalFrame {
    private ConnectionDB db;
    private Statement stmt;
    private String query;
    private ResultSet resultSet;
    
    String[] namaKolom = {
        "Id Pengontrak",
        "NIK",
        "Nama Pengontrak",
        "No Hp"
    };
    
    int jumlahKolom = namaKolom.length;
    TableModel modelTable = new TableModel();
    private String[][] rs;
    Pengontrak pengontrak = new Pengontrak();
    PengontrakDAO pDao = new PengontrakDAO();
    DefaultTableModel model;
    
    private void refreshTable(){
        Pengontrak pengontrak = new Pengontrak();
        rs = pDao.tampilDataPengontrak();
        modelTable.setTabel(tablePengontrak, rs, namaKolom, jumlahKolom);
    } 
    
    private void refreshForm(){
        tfIdPengontrak.setText("");
        tfNik.setText("");
        tfNamaPengontrak.setText("");
        tfNoHp.setText("");
    }
    
    /**
     * Creates new form MenuFasilitasInternalForm
     */
    public MenuPengontrakInternalFrame() {
        initComponents();
        refreshTable();        
    }

    private void setValuePengontrak(){
        pengontrak.setIdPengontrak(tfIdPengontrak.getText());
        pengontrak.setNamaPengontrak(tfNamaPengontrak.getText());
        pengontrak.setNik(tfNik.getText());
        pengontrak.setNoHp(tfNoHp.getText());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfIdPengontrak = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNamaPengontrak = new javax.swing.JTextField();
        tfNoHp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePengontrak = new javax.swing.JTable();
        tfCariNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        tfNik = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Vollkorn SemiBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 195, 154));
        jLabel1.setText("Menu Pengontrak");

        jLabel2.setFont(new java.awt.Font("Source Sans Pro", 0, 13)); // NOI18N
        jLabel2.setText("Id Pengontrak");

        tfIdPengontrak.setFont(new java.awt.Font("Source Sans Pro", 0, 13)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Source Sans Pro", 0, 13)); // NOI18N
        jLabel3.setText("NIK");

        jLabel5.setFont(new java.awt.Font("Source Sans Pro", 0, 13)); // NOI18N
        jLabel5.setText("Nama Pengontrak");

        tfNamaPengontrak.setFont(new java.awt.Font("Source Sans Pro", 0, 13)); // NOI18N

        tfNoHp.setFont(new java.awt.Font("Source Sans Pro", 0, 13)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Source Sans Pro", 0, 13)); // NOI18N
        jLabel7.setText("No Hp");

        btnSimpan.setBackground(new java.awt.Color(255, 255, 255));
        btnSimpan.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        tablePengontrak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Pengontrak", "NIK", "Nama Pengontrak", "No Hp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePengontrak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePengontrakMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePengontrak);

        tfCariNama.setFont(new java.awt.Font("Source Sans Pro", 0, 13)); // NOI18N

        jLabel4.setText("Pencarian berdasarkan nama pengontrak");

        btnCari.setBackground(new java.awt.Color(255, 255, 255));
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addGap(14, 14, 14)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfIdPengontrak, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNamaPengontrak, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(tfNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNik)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(tfCariNama, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCari))
                            .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCariNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnCari))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfIdPengontrak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfNamaPengontrak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here: 
        
        try {
            setValuePengontrak();
            if((tfIdPengontrak.getText().isEmpty()) || (tfNik.getText().isEmpty()) || 
               (tfNamaPengontrak.getText().isEmpty()) || (tfNoHp.getText().isEmpty())){
               
              JOptionPane.showMessageDialog(null, "FIELD TIDAK BOLEH KOSONG!", "WARNING", JOptionPane.ERROR_MESSAGE);
            }else{
                pDao.tambahDataPengontrak(
                tfIdPengontrak.getText(),           
                tfNik.getText(),
                tfNamaPengontrak.getText(),
                tfNoHp.getText()
                );
            }
            refreshTable();
            refreshForm();
        } catch (Exception e) {
            printStackTrace(e);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        setValuePengontrak();
        pDao.ubahDataPengontrak(
            pengontrak.getNik(),
            pengontrak.getNamaPengontrak(),            
            pengontrak.getNoHp(),
            pengontrak.getIdPengontrak()
        );
        refreshTable();
        refreshForm();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void tablePengontrakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePengontrakMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = tablePengontrak.getSelectedRow();
        model = (DefaultTableModel) tablePengontrak.getModel();
        tfIdPengontrak.setText((String) model.getValueAt(selectedRowIndex, 0));
        tfIdPengontrak.setEditable(false);
        tfNik.setText((String) model.getValueAt(selectedRowIndex, 1));
        tfNamaPengontrak.setText((String) model.getValueAt(selectedRowIndex, 2));
        tfNoHp.setText((String) model.getValueAt(selectedRowIndex, 3));
    }//GEN-LAST:event_tablePengontrakMouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:        
        model = (DefaultTableModel) tablePengontrak.getModel();
        rs = pDao.cariNamaPengontrak(tfCariNama.getText());
        modelTable.setTabel(tablePengontrak, rs, namaKolom, jumlahKolom);
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        pDao.hapusDataPengontrak(tfIdPengontrak.getText());
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        refreshTable();
        refreshForm();
        tfIdPengontrak.setEditable(true);
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePengontrak;
    private javax.swing.JTextField tfCariNama;
    private javax.swing.JTextField tfIdPengontrak;
    private javax.swing.JTextField tfNamaPengontrak;
    private javax.swing.JTextField tfNik;
    private javax.swing.JTextField tfNoHp;
    // End of variables declaration//GEN-END:variables
}
