package transaksi;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author fikriadriansa21
 */
public class MenuTransaksiInternalFrame extends javax.swing.JInternalFrame {
    
    private ConnectionDB db;
    private Statement stmt;
    private String query;
    private ResultSet resultSet;
    
    String[] namaKolom = {
        "No Kontrakan",
        "Biaya",
        "Luas",
        "Status"
    };
    
    int jumlahKolom = namaKolom.length;
    TableModel modelTable = new TableModel();
    private String[][] rs;
    Transaksi transaksi = new Transaksi();
    DefaultTableModel model;
    
    
    private void refreshTable(){
        Transaksi transaksi = new Transaksi();
        rs = transaksi.tampilData();
        modelTable.setTabel(tableTransaksi, rs, namaKolom, jumlahKolom);
    }    
    
    private void refreshForm(){
        tfIdTransaksi.setText("");
        tanggalTransakiChooser.setToolTipText("");
        comboNoKontrakan.setSelectedItem("");
        comboIdPengontrak.setSelectedItem("");
    }
    /**
     * Creates new form MenuKontrakanForm
     */
    public MenuTransaksiInternalFrame() {
        initComponents();    
        refreshTable();
        tampilComboKontrakan();
        tampilComboPengontrak();
    }

    public void tampilComboKontrakan(){
        try {
            db = new ConnectionDB();
            db.dbConnect();
        
            stmt = db.conection.createStatement();
            String sql = "select no_kontrakan from kontrakan ORDER BY no_kontrakan asc";      
            resultSet = stmt.executeQuery(sql);                                
        
            while(resultSet.next()){
                Object[] ob = new Object[1];
                ob[0] = resultSet.getString(1);

                comboNoKontrakan.addItem((String) ob[0]);                                      
            }
            resultSet.close(); stmt.close();

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
    }
    
    public void tampilComboPengontrak(){
        try {
            db = new ConnectionDB();
            db.dbConnect();
        
            stmt = db.conection.createStatement();
            String sql = "select id_pengontrak from pengontrak ORDER BY id_pengontrak asc";      
            resultSet = stmt.executeQuery(sql);                                
        
            while(resultSet.next()){
                Object[] ob = new Object[1];
                ob[0] = resultSet.getString(1);

                comboIdPengontrak.addItem((String) ob[0]);                                      
            }
            resultSet.close(); stmt.close();

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
    }
//    public String[][] tampilDataCari(){
//        rs = null;
//        String[][] data = null;
//        db = new ConnectionDB();
//        db.dbConnect();
//        int jumlahBaris = 0;
//        
//        try {
//            stmt = db.conection.createStatement();
//            query = "SELECT COUNT(no_kontrakan) as jumlah FROM kontrakan;";
//            resultSet = stmt.executeQuery(query);
//            if (resultSet.next()) {
//                jumlahBaris = resultSet.getInt("jumlah");
//                        
//            }
//            query = "SELECT * FROM kontrakan WHERE status = '"+comboStatus.getSelectedItem()+"';";
//            resultSet = stmt.executeQuery(query);
//            data = new String[jumlahBaris][4];
//            int r = 0;
//            
//            while (resultSet.next()) {                
//                data[r][0] = resultSet.getString("no_kontrakan");
//                data[r][1] = resultSet.getString("harga_kontrakan");
//                data[r][2] = resultSet.getString("luas_kontrakan");
//                data[r][3] = resultSet.getString("status");
//                r++;
//            }
//            stmt.close();
//            db.conection.close();
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
//        }
//        return data;
//    }
//    private void tampilCari(){        
//        rs = tampilDataCari();
//        modelTable.setTabel(tableTransaksi, rs, namaKolom, jumlahKolom);
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfIdTransaksi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        tanggalTransakiChooser = new com.toedter.calendar.JDateChooser();
        comboNoKontrakan = new javax.swing.JComboBox<>();
        comboIdPengontrak = new javax.swing.JComboBox<>();
        comboCariTanggal = new com.toedter.calendar.JDateChooser();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Vollkorn SemiBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 195, 154));
        jLabel1.setText("Menu Transaksi");

        jLabel2.setFont(new java.awt.Font("Source Sans Pro", 0, 13)); // NOI18N
        jLabel2.setText("Id Transaksi");

        tfIdTransaksi.setFont(new java.awt.Font("Source Sans Pro", 0, 13)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Source Sans Pro", 0, 13)); // NOI18N
        jLabel3.setText("Tanggal");

        jLabel5.setFont(new java.awt.Font("Source Sans Pro", 0, 13)); // NOI18N
        jLabel5.setText("No Kontrakan");

        jLabel7.setFont(new java.awt.Font("Source Sans Pro", 0, 13)); // NOI18N
        jLabel7.setText("Id Pengontrak");

        btnSimpan.setBackground(new java.awt.Color(255, 255, 255));
        btnSimpan.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Source Sans Pro", 0, 13)); // NOI18N
        jLabel8.setText("Pencarian berdasarkan tanggal transaksi");

        btnCari.setBackground(new java.awt.Color(255, 255, 255));
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Transaksi", "Tanggal", "No Kontrakan", "Nama Pengontrak"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTransaksi);

        btnUbah.setBackground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");

        tanggalTransakiChooser.setBackground(new java.awt.Color(255, 255, 255));

        comboNoKontrakan.setBackground(new java.awt.Color(255, 255, 255));

        comboIdPengontrak.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(849, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSimpan)
                        .addGap(14, 14, 14)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfIdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tanggalTransakiChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(comboIdPengontrak, javax.swing.GroupLayout.Alignment.LEADING, 0, 100, Short.MAX_VALUE)
                                .addComponent(comboNoKontrakan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnHapus)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(29, 29, 29)
                        .addComponent(comboCariTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCari)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfIdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tanggalTransakiChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(comboNoKontrakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(comboIdPengontrak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(323, 323, 323))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCari)
                            .addComponent(jLabel8)
                            .addComponent(comboCariTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(311, 311, 311))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
                
        
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:   
//        Kontrakan kontrakan = new Kontrakan();
//            kontrakan.tambahData(
//                    tfIdTransaksi.getText(),
//                    new Double(tfBiayaKontrakan.getText()),
//                    new Double(tfLuasKontrakan.getText()),
//                    tfStatusKontrakan.getText());

        refreshTable();
        refreshForm();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
//        Kontrakan kontrakan = new Kontrakan(); 
//        
//            kontrakan.ubahData(
//                    new Double(tfBiayaKontrakan.getText()),
//                    new Double(tfLuasKontrakan.getText()),
//                    tfStatusKontrakan.getText(),
//                    tfIdTransaksi.getText()); 
//        refreshTable();
//        refreshForm();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void tableTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransaksiMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = tableTransaksi.getSelectedRow();
        model = (DefaultTableModel) tableTransaksi.getModel();
        
        tfIdTransaksi.setText((String) model.getValueAt(selectedRowIndex, 0));
        tfIdTransaksi.setEditable(false);
        tanggalTransakiChooser.setToolTipText((String) model.getValueAt(selectedRowIndex, 1));
        comboNoKontrakan.setSelectedItem((String) model.getValueAt(selectedRowIndex, 2));
        comboIdPengontrak.setSelectedItem((String) model.getValueAt(selectedRowIndex, 3));

    }//GEN-LAST:event_tableTransaksiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private com.toedter.calendar.JDateChooser comboCariTanggal;
    private javax.swing.JComboBox<String> comboIdPengontrak;
    private javax.swing.JComboBox<String> comboNoKontrakan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTransaksi;
    private com.toedter.calendar.JDateChooser tanggalTransakiChooser;
    private javax.swing.JTextField tfIdTransaksi;
    // End of variables declaration//GEN-END:variables
}
