package main;

import kontrakan.MenuKontrakanInternalFrame;
import fasilitas.MenuFasilitasInternalFrame;
import pengontrak.MenuPengontrakInternalFrame;
import transaksi.MenuTransaksiInternalFrame;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fikriadriansa21
 */
public class MainForm extends javax.swing.JFrame {
    MenuKontrakanInternalFrame formKontrakan = new MenuKontrakanInternalFrame();
    MenuFasilitasInternalFrame formFasilitas = new MenuFasilitasInternalFrame();
    MenuPengontrakInternalFrame formPengontrak = new MenuPengontrakInternalFrame();
    MenuTransaksiInternalFrame formTransaksi = new MenuTransaksiInternalFrame();
    
    /**
     * Creates new form MenuUtama
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DesktopMenu = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuKontrakan = new javax.swing.JMenuItem();
        menuPengontrak = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenuItem();
        menuFasilitas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Vollkorn SemiBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 195, 154));
        jLabel1.setText("CariKontrakan");

        DesktopMenu.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(DesktopMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 1095, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(DesktopMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        menuKontrakan.setText("Data Kontrakan");
        menuKontrakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKontrakanActionPerformed(evt);
            }
        });
        jMenu1.add(menuKontrakan);

        menuPengontrak.setText("Data Pengontrak");
        menuPengontrak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPengontrakActionPerformed(evt);
            }
        });
        jMenu1.add(menuPengontrak);

        menuTransaksi.setText("Data Transaksi");
        menuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransaksiActionPerformed(evt);
            }
        });
        jMenu1.add(menuTransaksi);

        menuFasilitas.setText("Data Fasilitas");
        menuFasilitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFasilitasActionPerformed(evt);
            }
        });
        jMenu1.add(menuFasilitas);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuKontrakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKontrakanActionPerformed
        // TODO add your handling code here:
        DesktopMenu.add(formKontrakan,0);
        formKontrakan.setVisible(true);
        formPengontrak.setVisible(false);
        formFasilitas.setVisible(false);
        formTransaksi.setVisible(false);
    }//GEN-LAST:event_menuKontrakanActionPerformed

    private void menuPengontrakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPengontrakActionPerformed
        // TODO add your handling code here:
        DesktopMenu.add(formPengontrak,1);
        formPengontrak.setVisible(true);
        formKontrakan.setVisible(false);
        formFasilitas.setVisible(false);
        formTransaksi.setVisible(false);
    }//GEN-LAST:event_menuPengontrakActionPerformed

    private void menuFasilitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFasilitasActionPerformed
        // TODO add your handling code here:
        DesktopMenu.add(formFasilitas,3);
        formFasilitas.setVisible(true);
        formKontrakan.setVisible(false);
        formPengontrak.setVisible(false);
        formTransaksi.setVisible(false);
    }//GEN-LAST:event_menuFasilitasActionPerformed

    private void menuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransaksiActionPerformed
        // TODO add your handling code here:
        DesktopMenu.add(formTransaksi,2);
        formTransaksi.setVisible(true);
        formFasilitas.setVisible(false);
        formKontrakan.setVisible(false);
        formPengontrak.setVisible(false);
    }//GEN-LAST:event_menuTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuFasilitas;
    private javax.swing.JMenuItem menuKontrakan;
    private javax.swing.JMenuItem menuPengontrak;
    private javax.swing.JMenuItem menuTransaksi;
    // End of variables declaration//GEN-END:variables
}
