/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fasilitas;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.objects.NativeError.printStackTrace;
import model.ConnectionDB;
import model.Fasilitas;
import model.TableModel;

/**
 *
 * @author fikriadriansa21
 */
public class MenuFasilitasInternalFrame extends javax.swing.JInternalFrame {
    private ConnectionDB db;
    private Statement stmt;
    private String query;
    private ResultSet resultSet;
    
    String[] namaKolom = {
        "Id Fasilitas",
        "No Kontrakan",
        "Nama Fasilitas",
        "Jumlah"
    };
    
    int jumlahKolom = namaKolom.length;
    TableModel modelTable = new TableModel();
    private String[][] rs;
    Fasilitas fasilitas = new Fasilitas();
    DefaultTableModel model;
    private FasilitasDAO fDao = new FasilitasDAO();
    
    
    private void refreshTable(){        
        rs = fDao.tampilDataFasilitas();
        modelTable.setTabel(tableFasilitas, rs, namaKolom, jumlahKolom);
    } 
    
    private void refreshForm(){
        tfIdFasilitas.setText("");
        comboNoKontrakan.setSelectedItem("");
        tfNamaFasilitas.setText("");
        tfJumlah.setText("");
    }
    
    public void tampilComboKontrakan(){
        try {
            db = new ConnectionDB();
            db.dbConnect();
        
            stmt = db.conection.createStatement();
            String sql = "select no_kontrakan from kontrakan ORDER BY no_kontrakan asc";      
            resultSet = stmt.executeQuery(sql);                                
        
            while(resultSet.next()){
                Object[] ob = new Object[1];
                ob[0] = resultSet.getString(1);

                comboNoKontrakan.addItem((String) ob[0]);                                      
            }
            resultSet.close(); stmt.close();

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
    }
    /**
     * Creates new form MenuFasilitasInternalForm
     */
    public MenuFasilitasInternalFrame() {
        initComponents();
        refreshTable();
        tampilComboKontrakan();
    }

    private void setValueFasilitas(){
        fasilitas.setIdFasilitas(tfIdFasilitas.getText());
        fasilitas.setNoKontrakan(String.valueOf(comboNoKontrakan.getSelectedItem()));
        fasilitas.setNamaFasilitas(tfNamaFasilitas.getText());
        fasilitas.setJumlah(new Integer(tfJumlah.getText()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfIdFasilitas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNamaFasilitas = new javax.swing.JTextField();
        tfJumlah = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        comboNoKontrakan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFasilitas = new javax.swing.JTable();
        tfCariFasilitas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Vollkorn SemiBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 195, 154));
        jLabel1.setText("Menu Fasilitas");

        jLabel2.setFont(new java.awt.Font("Source Sans Pro", 0, 13)); // NOI18N
        jLabel2.setText("Id Fasilitas");

        tfIdFasilitas.setFont(new java.awt.Font("Source Sans Pro", 0, 13)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Source Sans Pro", 0, 13)); // NOI18N
        jLabel3.setText("No Kontrakan");

        jLabel5.setFont(new java.awt.Font("Source Sans Pro", 0, 13)); // NOI18N
        jLabel5.setText("Nama Fasilitas");

        tfNamaFasilitas.setFont(new java.awt.Font("Source Sans Pro", 0, 13)); // NOI18N

        tfJumlah.setFont(new java.awt.Font("Source Sans Pro", 0, 13)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Source Sans Pro", 0, 13)); // NOI18N
        jLabel7.setText("Jumlah");

        btnSimpan.setBackground(new java.awt.Color(255, 255, 255));
        btnSimpan.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        comboNoKontrakan.setBackground(new java.awt.Color(255, 255, 255));
        comboNoKontrakan.setFont(new java.awt.Font("Source Sans Pro", 0, 13)); // NOI18N

        tableFasilitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Fasilitas", "No Kontrakan", "Nama Fasilitas", "Jumlah"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableFasilitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFasilitasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableFasilitas);

        tfCariFasilitas.setFont(new java.awt.Font("Source Sans Pro", 0, 13)); // NOI18N

        jLabel4.setText("Pencarian berdasarkan nama fasilitas");

        btnCari.setBackground(new java.awt.Color(255, 255, 255));
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addGap(14, 14, 14)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfIdFasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboNoKontrakan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNamaFasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(32, 32, 32)
                        .addComponent(tfCariFasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCari))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCariFasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnCari))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfIdFasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(comboNoKontrakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfNamaFasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:        
        try { 
            setValueFasilitas();
            if((tfIdFasilitas.getText().isEmpty()) || (tfNamaFasilitas.getText().isEmpty()) ||
              (tfJumlah.getText().isEmpty())){
                JOptionPane.showMessageDialog(null, "FIELD TIDAK BOLEH KOSONG!", "WARNING", JOptionPane.ERROR_MESSAGE);

            } else {
                fDao.tambahDataFasilitas(
                tfIdFasilitas.getText(),           
                String.valueOf(comboNoKontrakan.getSelectedItem()),
                tfNamaFasilitas.getText(),
                Integer.valueOf(tfJumlah.getText())
                );
            }
            refreshTable();
            refreshForm();
        } catch (Exception e) {
            printStackTrace(e);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here: 
        setValueFasilitas();
        fDao.ubahDataFasilitas(                       
            fasilitas.getNoKontrakan(),
            fasilitas.getNamaFasilitas(),
            fasilitas.getJumlah(),
            fasilitas.getIdFasilitas()
        );
        refreshTable();
        refreshForm();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void tableFasilitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFasilitasMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = tableFasilitas.getSelectedRow();
        model = (DefaultTableModel) tableFasilitas.getModel();
        tfIdFasilitas.setText((String) model.getValueAt(selectedRowIndex, 0));
        tfIdFasilitas.setEditable(false);
        comboNoKontrakan.setSelectedItem((String) model.getValueAt(selectedRowIndex, 1));
        tfNamaFasilitas.setText((String) model.getValueAt(selectedRowIndex, 2));
        tfJumlah.setText((String) model.getValueAt(selectedRowIndex, 3));
    }//GEN-LAST:event_tableFasilitasMouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:        
        model = (DefaultTableModel) tableFasilitas.getModel();
        rs = fDao.cariNamaFasilitas(tfCariFasilitas.getText());
        modelTable.setTabel(tableFasilitas, rs, namaKolom, jumlahKolom);
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:        
        fDao.hapusDataFasilitas(fasilitas.getIdFasilitas());
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        refreshTable();
        refreshForm();
        tfIdFasilitas.setEditable(true);
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> comboNoKontrakan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableFasilitas;
    private javax.swing.JTextField tfCariFasilitas;
    private javax.swing.JTextField tfIdFasilitas;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JTextField tfNamaFasilitas;
    // End of variables declaration//GEN-END:variables
}